name: Build Environments
on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux-arm64
            arch: arm64v8
            os: linux
            buildx-arch: linux/arm64
          - platform: linux-arm32
            arch: arm32v7
            os: linux
            buildx-arch: linux/arm/v7
          - platform: linux-x64
            arch: x86_64
            os: linux
            buildx-arch: linux/amd64
          - platform: linux-x86
            arch: i686
            os: linux
            buildx-arch: linux/386
    name: ${{ matrix.platform }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        env:
          USE_R2_MIRROR: 1
          PLATFORM: ${{ matrix.platform }}
          BUILDX_ARCH: ${{ matrix.buildx-arch }}
          ARCH: ${{ matrix.arch }}
          SYSROOT_IMAGE_NAME: tmbasic-linux-sysroot
        run: |
          set -euxo pipefail
          find . -type f -name "*.sh" -exec chmod +x {} \;

          # Generate the build/files/sysroot-$ARCH.tar.gz file.
          pushd build/sysroots
          IMAGE_NAME=$SYSROOT_IMAGE_NAME ./build.sh
          popd

          # Build the build environment container.
          export IMAGE_NAME="tmbasic-build-env"
          pushd build
          BUILD_ONLY=1 ./${{ matrix.platform }}.sh
          popd

          # Save the build environment container (not just the root filesystem) to a tarball.
          docker save "$IMAGE_NAME" | gzip -c > "tmbasic-build-env-${{ matrix.platform }}.tar.gz"

      - name: Upload environment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: tmbasic-build-env-${{ matrix.platform }}.tar.gz

  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - platform: win-arm64
          - platform: win-x64
          - platform: win-x86
    name: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          $ErrorActionPreference = "Stop"

          Write-Host "Building environment."
          build\${{ matrix.platform }}.ps1 -BuildDeps -BuildType Release -UseR2Mirror

          Write-Host "Archiving environment."
          $filename = "tmbasic-build-env-${{ matrix.platform }}.zip"
          Compress-Archive -Path "${{ matrix.platform }}", "win-native" -DestinationPath "$filename"

      - name: Upload environment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: tmbasic-build-env-${{ matrix.platform }}.zip

  build-mac:
    # Our build process requires an M1 Mac; it won't work on an Intel Mac.
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - platform: mac-arm64
            short_arch: arm64
          - platform: mac-x64
            short_arch: x64
    name: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        env:
          USE_R2_MIRROR: 1
        run: |
          set -euxo pipefail
          find . -type f -name "*.sh" -exec chmod +x {} \;

          echo "Installing GNU sed."
          brew install gnu-sed
          export PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"

          echo "Building environment."
          pushd build
          ./${{ matrix.platform }}.sh
          popd

          echo "Archiving environment."
          export FILENAME=tmbasic-build-env-${{ matrix.platform }}.tar.gz
          tar zcf "$FILENAME" "mac-${{ matrix.short_arch }}"

      - name: Upload environment
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: tmbasic-build-env-${{ matrix.platform }}.tar.gz

  upload:
    name: Upload to R2
    runs-on: ubuntu-latest
    needs: [build-linux, build-win, build-mac]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload all artifacts to R2
        run: |
          set -euxo pipefail

          # Collect all .tar.gz and .zip files and move them to the root
          find . -type f -name "*.tar.gz" -exec mv {} . \;
          find . -type f -name "*.zip" -exec mv {} . \;
          ls -lR

          # Verify artifacts exist
          for platform in linux-arm64 linux-arm32 linux-x64 linux-x86 mac-arm64 mac-x64; do
            if [ ! -f "tmbasic-build-env-${platform}.tar.gz" ]; then
              echo "Error: tmbasic-build-env-${platform}.tar.gz does not exist"
              exit 1
            fi
          done

          for platform in win-arm64 win-x64 win-x86; do
            if [ ! -f "tmbasic-build-env-${platform}.zip" ]; then
              echo "Error: tmbasic-build-env-${platform}.zip does not exist"
              exit 1
            fi
          done

          # Upload artifacts to R2
          timestamp=$(date -u "+%Y%m%d%H%M%S")
          for platform in linux-arm64 linux-arm32 linux-x64 linux-x86; do
            aws s3 cp \
              --endpoint "$R2_ENDPOINT" \
              --checksum-algorithm CRC32 \
              "tmbasic-build-env-${platform}.tar.gz" \
              "s3://tmbasic-archive/linux-build-envs/tmbasic-build-env-${platform}-${timestamp}.tar.gz"
          done

          for platform in mac-arm64 mac-x64; do
            aws s3 cp \
              --endpoint "$R2_ENDPOINT" \
              --checksum-algorithm CRC32 \
              "tmbasic-build-env-${platform}.tar.gz" \
              "s3://tmbasic-archive/mac-build-envs/tmbasic-build-env-${platform}-${timestamp}.tar.gz"
          done

          for platform in win-arm64 win-x64 win-x86; do
            aws s3 cp \
              --endpoint "$R2_ENDPOINT" \
              --checksum-algorithm CRC32 \
              "tmbasic-build-env-${platform}.zip" \
              "s3://tmbasic-archive/win-build-envs/tmbasic-build-env-${platform}-${timestamp}.zip"
          done

      - name: Delete intermediate artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: |
            linux-arm64
            linux-arm32
            linux-x64
            linux-x86
            win-arm64
            win-x64
            win-x86
