name: linux-sysroots
on: workflow_dispatch

jobs:
  build:
    name: linux-sysroots
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: cd build/sysroots && ./buildArmSysroots.sh && ./buildIntelSysroots.sh
